[workspace]
members = [
    "common",
    "main/contract",
    "main/tests",
    "price-oracle/contract",
    "nft-core/contract",
    "nft-core/client/*",
    "nft-contract/contract",
    "authorities/contract",
    "authorities/tests",
    "database/contract",
    "tests"
]