[workspace]
members = [
    "common",
    "configuration/contract",
    "configuration/tests",
    "main/contract",
    "price-oracle/contract",
    "nft-core/contract",
    "nft-core/client/*",
    "nft-contract/contract",
    "database/contract",
    "registry/contract",
    "tests",
]
