[workspace]
members = [
    "temp/contract",
    "temp/tests",
    "common",
    "main/contract",
    "price-oracle/contract",
    "nft-core/contract",
    "nft-core/client/*",
    "nft-contract/contract",
    "database/contract",
    "registry/contract",
    "tests"
    
]